### ISSUE TITLE
Clear color not working on mac OS

### ISSUE THREAD

**Issue by fraca7** [ParisNeo/QPanda3D#1]
Hello. The following example works fine under Ubuntu 17.10 (panda3d 1.10.2, Qt 5.12.2, glxGraphicsPipe), but under mac OS Mojave (panda3d 1.10.2, Qt 5.11.1, CocoaGraphicsPipe) the clear color seems not to be active; the background stays black and "older" pixels are not cleared.

```
#!/usr/bin/env python3

import math

from PyQt5 import QtWidgets

from QPanda3D.QPanda3DWidget import QPanda3DWidget
from QPanda3D.Panda3DWorld import Panda3DWorld

from direct.task import Task
from panda3d.core import VBase4


class World(Panda3DWorld):
    def __init__(self):
        super().__init__()

        self.win.setClearColorActive(True)
        self.win.setClearColor(VBase4(0, 0.5, 0, 1))

        self.taskMgr.add(self.spinCameraTask, 'SpinCameraTask')

        self._model = self.loader.loadModel('models/panda-model')
        self._model.reparentTo(self.render)

    def spinCameraTask(self, task):
        angle = task.time * 6 * math.pi / 180
        self.camera.setPos(20 * math.sin(angle), -20 * math.cos(angle), 3)
        self.camera.setHpr(angle * 180 / math.pi, 0, 0)
        return Task.cont


class TestWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        widget = QPanda3DWidget(World(), self, stretch=True, keep_ratio=True)
        self.setCentralWidget(widget)

        self.resize(800, 600)
        self.show()
        self.raise_()


if __name__ == '__main__':
    app = QtWidgets.QApplication([])
    win = TestWindow()
    app.exec_()
```

Any idea ?

**Comment by fraca7** [comment]
Aaaand found out a workaround. What I didn't notice was the following warning:

```
:display(warning): FrameBufferProperties available less than requested.
  requested: depth_bits=1 color_bits=3 red_bits=1 green_bits=1 blue_bits=1 alpha_bits=1 back_buffers=1 force_hardware 
  got: depth_bits=24 color_bits=24 red_bits=8 green_bits=8 blue_bits=8 alpha_bits=8 stencil_bits=8 force_hardware 
```

After a bit of digging (total newbie here) I added

`loadPrcFileData('', 'back-buffers 0')
`

before the call to `super().__init__` in `World.__init__` and that does the trick. If I can find a way to automatically detect if this needs to be done, I'll make a pull request.

**Comment by ParisNeo** [comment]
Thanks and sorry for being so late.
I had no time lately.

I did accept your pull request but it did create a little problem on windows since you can't change the size of the win object. So I changed it alltogather by creating my own buffer with BF_resizable to rendrer to and set a new camera ... It was actually this problem that prevented me intiatially to do as you suggested.

But after some digging, I figured that I had to do this custom buffer creation.

Now it works like charm on windowsd too.

Thanks
