### ISSUE TITLE
Create a contributor's/maintainer's guide

### ISSUE THREAD

**Issue by majabojarska** [ParisNeo/QPanda3D#12]
I'd like to propose creating a contributor's/maintainer's guide. It would provide information about:

- preferred formatter & linter,
- docstring style,
- test framework,
- etc.

I can take care of this, however it would be good to discuss the details first :relaxed:.

My suggestions:
- formatter: black with default settings,
- linter: flake8,
- docstring style: numpy,
- test framework: pytest + tox,
- CI environment: GitHub Actions.

Then we could develop some automation scripts that would test against lint errors, run unit tests (if implemented) for different Python versions. This could be handled via tox's isolated test environments, both on a local machine and GitHub Actions.

**Comment by ParisNeo** [comment]
You are welcome to do those updates. Since I had no time at all last year and this year. Any help is welcomed.

**Comment by majabojarska** [comment]
Thanks for the answer. I'm quite busy at the time, but will get back to the topic when possible.
